export const block: string
export const inlineBlock: string
export const inline: string
export const hidden: string
export const xsBlock: string
export const xsInlineBlock: string
export const xsInline: string
export const xsHidden: string
export const smBlock: string
export const smInlineBlock: string
export const smInline: string
export const smHidden: string
export const mdBlock: string
export const mdInlineBlock: string
export const mdInline: string
export const mdHidden: string
export const lgBlock: string
export const lgInlineBlock: string
export const lgInline: string
export const lgHidden: string
export const xlBlock: string
export const xlInlineBlock: string
export const xlInline: string
export const xlHidden: string
