export const none: string;
export const negSmR: string;
export const negSmL: string;
export const negMdR: string;
export const negMdL: string;
export const negMdT: string;
export const xsNegSmR: string;
export const xsNegSmL: string;
export const printNoneT: string
